spring:
  application:
    name: project
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33306/hotel
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 33000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
